[workspace]
members = [
    "crates/carnelian-ast",
    "crates/carnelian-compiler",
    "crates/carnelian-front-prism",
    "crates/carnelian-cli",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
carnelian-ast = { path = "crates/carnelian-ast" }
carnelian-compiler = { path = "crates/carnelian-compiler" }
carnelian-front-prism = { path = "crates/carnelian-front-prism" }
