[workspace]
members = [
    "crates/carnelian-ast",
    "crates/carnelian-compiler",
    "crates/carnelian-front-prism",
    "crates/carnelian-front-mri",
    "crates/carnelian-cli",
    "crates/carnelian-playground",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.82"
license = "BSD-2-Clause"

[workspace.dependencies]
carnelian-ast = { path = "crates/carnelian-ast" }
carnelian-compiler = { path = "crates/carnelian-compiler" }
carnelian-front-prism = { path = "crates/carnelian-front-prism" }
carnelian-front-mri = { path = "crates/carnelian-front-mri" }
carnelian-playground = { path = "crates/carnelian-playground" }
