//! Owned Prism AST: 1:1 names/fields with Prism, no C, no FFI.
//!
//! The `Node` enum and visitor are generated by `build.rs` from the
//! `prism-1.9.0` `config.json` snapshot in `config/`.

use std::collections::BTreeMap;

pub mod view;

include!(concat!(env!("OUT_DIR"), "/node_generated.rs"));

/// Interned constant/symbol (`constant` fields in Prism).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SymbolId(pub u32);

/// Byte offsets into the source (`location` fields in Prism).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Span {
    /// Start byte offset.
    pub start: u32,
    /// End byte offset (exclusive).
    pub end: u32,
}

/// Integer literal model: `i64` when it fits `MRC_INT64`, otherwise the
/// original decimal bytes for a `LOADL` pool literal (`new_lit_int` in P2).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Integer {
    /// Value fits in `i64`.
    I64(i64),
    /// Overflow: raw decimal bytes, sign included.
    Fallback { raw: Vec<u8> },
}

impl Integer {
    /// Build from raw decimal bytes, mirroring `new_lit_int` range checks.
    /// Reserved for text-source frontends (P4 MRI); the Prism lowering
    /// normalizes to canonical digits itself instead of using this.
    #[must_use]
    pub fn from_decimal(raw: &[u8]) -> Self {
        let text = core::str::from_utf8(raw).unwrap_or("");
        let text = text.replace('_', "");
        if let Ok(value) = text.parse::<i64>() {
            Self::I64(value)
        } else {
            Self::Fallback { raw: raw.to_vec() }
        }
    }

    /// Value when it fits in `i64`.
    #[must_use]
    pub const fn as_i64(&self) -> Option<i64> {
        match *self {
            Self::I64(value) => Some(value),
            Self::Fallback { .. } => None,
        }
    }
}

/// Deterministic symbol pool: insertion order defines IDs.
#[derive(Debug, Default)]
pub struct SymbolPool {
    names: Vec<Vec<u8>>,
    index: BTreeMap<Vec<u8>, u32>,
}

impl SymbolPool {
    /// Empty pool.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Intern `name`, returning its stable ID.
    pub fn intern(&mut self, name: &[u8]) -> SymbolId {
        if let Some(&id) = self.index.get(name) {
            return SymbolId(id);
        }
        let id = self.names.len() as u32;
        self.names.push(name.to_vec());
        self.index.insert(name.to_vec(), id);
        SymbolId(id)
    }

    /// Look up an interned name.
    #[must_use]
    pub fn lookup(&self, id: SymbolId) -> Option<&[u8]> {
        self.names.get(id.0 as usize).map(Vec::as_slice)
    }

    /// Names in ID order.
    #[must_use]
    pub fn names(&self) -> &[Vec<u8>] {
        &self.names
    }
}

/// Thin node-access trait: the backend is written against this, so the
/// borrowed FFI frontend (P1) and the owned AST share handlers.
///
/// P0 exposes the traversal core; typed per-node accessors arrive with the
/// codegen tranches (P2) without changing this boundary.
pub trait AstNode {
    /// Prism kind name, 1:1 with `config.json`.
    fn kind_name(&self) -> &'static str;
    /// Node span.
    fn span(&self) -> Span;
    /// Raw Prism flags.
    fn flags(&self) -> u16;
}

impl AstNode for Node {
    fn kind_name(&self) -> &'static str {
        Node::kind_name(self)
    }

    fn span(&self) -> Span {
        Node::span(self)
    }

    fn flags(&self) -> u16 {
        Node::flags(self)
    }
}
