//! Owned Prism AST: 1:1 names/fields with Prism, no C, no FFI.
//!
//! The `Node` enum and visitor are generated by `build.rs` from the
//! `prism-1.9.0` `config.json` snapshot in `config/`.

use std::collections::BTreeMap;

pub mod owned;
pub mod view;

pub use owned::Owned;

include!(concat!(env!("OUT_DIR"), "/node_generated.rs"));

/// Interned constant/symbol (`constant` fields in Prism).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SymbolId(pub u32);

/// Byte offsets into the source (`location` fields in Prism).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Span {
    /// Start byte offset.
    pub start: u32,
    /// End byte offset (exclusive).
    pub end: u32,
}

/// Integer literal model: `i64` when it fits `MRC_INT64`, otherwise the
/// original decimal bytes for a `LOADL` pool literal (`new_lit_int` in P2).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Integer {
    /// Value fits in `i64`.
    I64(i64),
    /// Overflow: raw decimal bytes, sign included.
    Fallback { raw: Vec<u8> },
}

impl Integer {
    /// Build from raw decimal bytes, mirroring `new_lit_int` range checks.
    /// Reserved for text-source frontends (P4 MRI); the Prism lowering
    /// normalizes to canonical digits itself instead of using this.
    #[must_use]
    pub fn from_decimal(raw: &[u8]) -> Self {
        let text = core::str::from_utf8(raw).unwrap_or("");
        let text = text.replace('_', "");
        if let Ok(value) = text.parse::<i64>() {
            Self::I64(value)
        } else {
            Self::Fallback { raw: raw.to_vec() }
        }
    }

    /// Value when it fits in `i64`.
    #[must_use]
    pub const fn as_i64(&self) -> Option<i64> {
        match *self {
            Self::I64(value) => Some(value),
            Self::Fallback { .. } => None,
        }
    }
}

/// `PM_PARAMETER_FLAGS_NIL_BLOCK` of the patched reference Prism (`&nil`,
/// "method accepts no block"); upstream `ruby-prism` has no such constant,
/// so both frontends test this bit.
pub const NIL_BLOCK: u32 = 8;

/// Decimal digits of a little-endian base-2^32 limb slice, without leading
/// zeros (empty input reads as zero). Shared by the Prism and MRI
/// frontends; the owned accessor's `bigint_from_raw` reaches the same
/// canonical digits from decimal text instead of binary limbs.
#[must_use]
pub fn limbs_to_decimal(limbs: &[u32]) -> Vec<u8> {
    let mut words: Vec<u32> = limbs.to_vec();
    while words.last() == Some(&0) {
        words.pop();
    }
    if words.is_empty() {
        return vec![b'0'];
    }
    let mut digits = Vec::new();
    while !words.is_empty() {
        let mut remainder: u64 = 0;
        for index in (0..words.len()).rev() {
            let current = (remainder << 32) | u64::from(words[index]);
            words[index] = (current / 10) as u32;
            remainder = current % 10;
        }
        digits.push(b'0' + remainder as u8);
        while words.last() == Some(&0) {
            words.pop();
        }
    }
    digits.reverse();
    digits
}

/// Deterministic symbol pool: insertion order defines IDs.
#[derive(Debug, Default)]
pub struct SymbolPool {
    names: Vec<Vec<u8>>,
    index: BTreeMap<Vec<u8>, u32>,
    /// Source text under lowering, for span-based re-lexing done by
    /// frontends (e.g. splitting adjacent string literals that a parser
    /// folded). Absent unless a lowering entry point installs it.
    source: Option<Vec<u8>>,
}

impl SymbolPool {
    /// Empty pool.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Install the source text being lowered (copied once per compile).
    pub fn set_source(&mut self, bytes: &[u8]) {
        self.source = Some(bytes.to_vec());
    }

    /// Lowering source text, if installed.
    #[must_use]
    pub fn source(&self) -> Option<&[u8]> {
        self.source.as_deref()
    }

    /// Intern `name`, returning its stable ID.
    pub fn intern(&mut self, name: &[u8]) -> SymbolId {
        if let Some(&id) = self.index.get(name) {
            return SymbolId(id);
        }
        let id = self.names.len() as u32;
        self.names.push(name.to_vec());
        self.index.insert(name.to_vec(), id);
        SymbolId(id)
    }

    /// Look up an interned name.
    #[must_use]
    pub fn lookup(&self, id: SymbolId) -> Option<&[u8]> {
        self.names.get(id.0 as usize).map(Vec::as_slice)
    }

    /// Names in ID order.
    #[must_use]
    pub fn names(&self) -> &[Vec<u8>] {
        &self.names
    }
}

/// Thin node-access trait: the backend is written against this, so the
/// borrowed FFI frontend (P1) and the owned AST share handlers.
///
/// P0 exposes the traversal core; typed per-node accessors arrive with the
/// codegen tranches (P2) without changing this boundary.
pub trait AstNode {
    /// Prism kind name, 1:1 with `config.json`.
    fn kind_name(&self) -> &'static str;
    /// Node span.
    fn span(&self) -> Span;
    /// Raw Prism flags.
    fn flags(&self) -> u16;
}

impl AstNode for Node {
    fn kind_name(&self) -> &'static str {
        Node::kind_name(self)
    }

    fn span(&self) -> Span {
        Node::span(self)
    }

    fn flags(&self) -> u16 {
        Node::flags(self)
    }
}
