#!/bin/sh
# Fetch the pinned real-world Ruby corpus into `.corpus/` (gitignored).
#
# Pins (era of the pinned reference: `mruby-compiler2 0.5.0`, Prism 1.9.0):
#   mruby/mruby          tag 3.4.0  (mrblib, benchmark, mrbgems/*/mrblib, test/t)
#   picoruby/picoruby    tag 3.4.5  (mrbgems/*/mrblib)
#
# Usage: tools/fetch_corpus.sh [--force]
#   Without --force, existing checkouts are kept after verifying the tag.
#   Writes `.corpus/PROVENANCE` with the resolved SHAs.
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
DEST="$ROOT/.corpus"
FORCE=0

for arg in "$@"; do
    case "$arg" in
        --force) FORCE=1 ;;
        -h | --help)
            echo "usage: $0 [--force]"
            exit 0
            ;;
        *)
            echo "unknown argument: $arg" >&2
            exit 2
            ;;
    esac
done

command -v git >/dev/null 2>&1 || {
    echo "fetch_corpus: git not found" >&2
    exit 2
}

fetch_one() {
    # $1 = name, $2 = repo URL, $3 = tag, $4 = expected SHA
    name="$1"
    url="$2"
    tag="$3"
    expected="$4"
    dir="$DEST/$name"

    if [ -d "$dir/.git" ] && [ "$FORCE" -eq 0 ]; then
        if verify_pin "$dir" "$tag" "$expected"; then
            echo "fetch_corpus: $name already at $tag ($expected), skipping"
            return 0
        fi
        echo "fetch_corpus: $name pin mismatch, re-cloning"
    fi

    echo "fetch_corpus: cloning $url @ $tag"
    rm -rf "$dir"
    mkdir -p "$DEST"
    tmpdir="$DEST/.tmp-$name"
    rm -rf "$tmpdir"
    git clone --depth 1 --branch "$tag" "$url" "$tmpdir"
    mv "$tmpdir" "$dir"
    verify_pin "$dir" "$tag" "$expected" || {
        echo "fetch_corpus: $name FAILED pin check, removing $dir" >&2
        rm -rf "$dir"
        exit 1
    }
    echo "fetch_corpus: $name -> $expected"
}

# Fail loudly unless $1 is a valid repo whose HEAD is exactly $3 and whose
# tag $2 resolves to the same commit. Never silently fall through to an
# outer repository (a broken nested .git makes plain `git -C` do that).
verify_pin() {
    dir="$1"
    tag="$2"
    expected="$3"
    gitdir="$(git -C "$dir" rev-parse --absolute-git-dir 2>/dev/null)" || return 1
    case "$gitdir" in
        "$dir"/.git) ;;
        *)
            echo "fetch_corpus: $dir resolves to outer repo $gitdir" >&2
            return 1
            ;;
    esac
    head="$(git -C "$dir" rev-parse HEAD)" || return 1
    [ "$head" = "$expected" ] || {
        echo "fetch_corpus: $dir HEAD $head != $expected" >&2
        return 1
    }
    resolved="$(git -C "$dir" rev-list -n 1 "$tag" 2>/dev/null)" || return 1
    [ "$resolved" = "$expected" ] || {
        echo "fetch_corpus: $dir tag $tag resolves to $resolved, want $expected" >&2
        return 1
    }
}

# Copies of the fetched trees pruned to Ruby sources only. The nested
# `.git` is moved aside for the whole prune and restored after: this is the
# only ordering-proof way to keep it intact (`-prune` does not combine with
# `-delete`, and `*` in `-path` never crosses `/`, so deep `.git` contents
# would slip through exclusions). `verify_pin` rejects anything that does
# not resolve inside the nested repo, so a broken restore fails loudly.
prune_one() {
    # $1 = name
    dir="$DEST/$1"
    gitdir="$DEST/.git-$1"
    rm -rf "$gitdir"
    mv "$dir/.git" "$gitdir"
    # Drop Ruby sources outside the corpus globs. mruby: mrblib/,
    # benchmark/, mrbgems/*/mrblib/, test/t/. picoruby: mrbgems/*/mrblib/.
    find "$dir" -type f -name '*.rb' \
        ! -path "$dir/mrblib/*" \
        ! -path "$dir/benchmark/*" \
        ! -path "$dir/mrbgems/*/mrblib/*" \
        ! -path "$dir/test/t/*" \
        -delete
    # Drop everything that is not a kept Ruby source (C, configs, docs…);
    # provenance (URLs, tags, SHAs, licenses) lives in PROVENANCE.
    find "$dir" -type f ! -name '*.rb' -delete
    # Drop symlinks (dangling build-config shims, vendored blobs): none of
    # the corpus trees keep sources behind links (verified: the only `.rb`
    # links sit outside the corpus globs).
    find "$dir" -type l -delete
    # Drop emptied trees to keep the cache small.
    find "$dir" -mindepth 1 -type d -empty -delete
    mv "$gitdir" "$dir/.git"
}

# Pinned SHAs (tags must resolve to exactly these; see verify_pin).
MRUBY_SHA=a309524d0bc90eef077a24634db2495a6f68e318
PICORUBY_SHA=d482862af826996fcaa65a42de5e6e51b6ed70c3

fetch_one mruby https://github.com/mruby/mruby.git 3.4.0 "$MRUBY_SHA"
fetch_one picoruby https://github.com/picoruby/picoruby.git 3.4.5 "$PICORUBY_SHA"

prune_one mruby
prune_one picoruby

{
    echo "# Real-world Ruby corpus provenance (generated by tools/fetch_corpus.sh)"
    echo "# Third-party sources, MIT licensed; never committed (see .gitignore)."
    echo "# Regenerate: tools/fetch_corpus.sh [--force]"
    echo ""
    for name in mruby picoruby; do
        sha="$(git -C "$DEST/$name" rev-parse HEAD)"
        tag="$(git -C "$DEST/$name" describe --tags --exact-match 2>/dev/null || echo "?")"
        count="$(find "$DEST/$name" -name '*.rb' | wc -l)"
        echo "$name tag=$tag sha=$sha files=$count"
    done
} >"$DEST/PROVENANCE"

cat "$DEST/PROVENANCE"
total="$(find "$DEST" -name '*.rb' -not -path "$DEST/.tmp-*" | wc -l)"
echo "fetch_corpus: $total Ruby files under $DEST"
